In [3]:
# Add dependencies
import glob
import pandas as pd

In [4]:
# Combine all the csv data into a new csv

clean_data = pd.concat([pd.read_csv(f) for f in glob.glob('citibike_data/*.csv')], ignore_index = True)

In [5]:
# Display results
clean_data.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2

In [6]:
# Get a count of the data in each column to see if they match
clean_data.count()

tripduration               336802
starttime                  336802
stoptime                   336802
start station id           336802
start station name         336802
start station latitude     336802
start station longitude    336802
end station id             336802
end station name           336802
end station latitude       336802
end station longitude      336802
bikeid                     336802
usertype                   336802
birth year                 336802
gender                     336802
dtype: int64

In [7]:
# 
clean_data.gender[clean_data.gender == 0] = 'unknown'
clean_data.gender[clean_data.gender == 1] = 'male'
clean_data.gender[clean_data.gender == 2] = 'female'
clean_data.head()

C:\Users\Kim\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,female
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,female
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,male
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,unknown
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,female

In [8]:
# Export to csv
clean_data.to_csv('clean_data/cleandata2020.csv', mode = 'w', index=False)

In [11]:
# Import Data
Data_To_Load1 = "citibike_data/JC-202001-citibike-tripdata.csv"

january_data = pd.read_csv(Data_To_Load1)

In [14]:
january_data.max()

tripduration                                 520598
starttime                  2020-01-31 23:48:35.1700
stoptime                   2020-02-01 00:00:36.4060
start station id                               3792
start station name                          York St
start station latitude                      40.7487
start station longitude                    -74.0321
end station id                                 3792
end station name                            York St
end station latitude                        40.7559
end station longitude                      -74.0021
bikeid                                        42370
usertype                                 Subscriber
birth year                                     2002
gender                                            2
dtype: object

In [15]:
january_data['birth year'].min()

1888

In [16]:
january_data['tripduration'].median()

326.0

In [17]:
january_data['birth year'].head()

0    1984
1    1989
2    1989
3    1969
4    1983
Name: birth year, dtype: int64

In [19]:
birthyearsort = january_data.sort_values('birth year', ascending = True)
birthyearsort.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
6682,97,2020-01-09 17:45:17.0690,2020-01-09 17:46:54.3580,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,29207,Subscriber,1888,0
11171,82,2020-01-14 07:32:59.8460,2020-01-14 07:34:22.4420,3275,Columbus Drive,40.718355,-74.038914,3187,Warren St,40.721124,-74.038051,26177,Subscriber,1888,0
22827,115,2020-01-28 19:19:42.9670,2020-01-28 19:21:38.5720,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,29480,Subscriber,1888,0
17155,89,2020-01-22 07:52:17.4500,2020-01-22 07:53:46.8910,3275,Columbus Drive,40.718355,-74.038914,3187,Warren St,40.721124,-74.038051,26257,Subscriber,1888,0
7949,105,2020-01-10 19:20:29.7050,2020-01-10 19:22:14.8400,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,29592,Subscriber,1888,0

In [21]:
january_data.loc[january_data['birth year'] < 1919]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
2667,141,2020-01-05 09:38:17.6380,2020-01-05 09:40:39.6170,3275,Columbus Drive,40.718355,-74.038914,3639,Harborside,40.719252,-74.034234,29640,Subscriber,1888,0
3193,74,2020-01-06 07:36:38.4470,2020-01-06 07:37:52.7620,3275,Columbus Drive,40.718355,-74.038914,3187,Warren St,40.721124,-74.038051,29463,Subscriber,1888,0
6682,97,2020-01-09 17:45:17.0690,2020-01-09 17:46:54.3580,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,29207,Subscriber,1888,0
7949,105,2020-01-10 19:20:29.7050,2020-01-10 19:22:14.8400,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,29592,Subscriber,1888,0
11171,82,2020-01-14 07:32:59.8460,2020-01-14 07:34:22.4420,3275,Columbus Drive,40.718355,-74.038914,3187,Warren St,40.721124,-74.038051,26177,Subscriber,1888,0
12788,95,2020-01-15 17:47:12.3450,2020-01-15 17:48:48.1690,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,29446,Subscriber,1888,0
13255,80,2020-01-16 07:34:13.8290,2020-01-16 07:35:34.4480,3275,Columbus Drive,40.718355,-74.038914,3187,Warren St,40.721124,-74.038051,29548,Subscriber,1888,0
14074,78,2020-01-16 19:33:28.1540,2020-01-16 19:34:46.1840,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,29262,Subscriber,1888,0
14904,103,2020-01-17 20:21:52.5510,2020-01-17 20:23:35.9350,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,29587,Subscriber,1888,0
17155,89,2020-01-22 07:52:17.4500,2020-01-22 07:53:46.8910,3275,Columbus Drive,40.718355,-74.038914,3187,Warren St,40.721124,-74.038051,26257,Subscriber,1888,0
18147,102,2020-01-23 07:47:58.8340,2020-01-23 07:49:41.6230,3275,Columbus Drive,40.718355,-74.038914,3187,Warren St,40.721124,-74.038051,26171,Subscriber,1888,0
21789,100,2020-01-27 19:13:42.6940,2020-01-27 19:15:22.9310,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,26278,Subscriber,1888,0
22827,115,2020-01-28 19:19:42.9670,2020-01-28 19:21:38.5720,3187,Warren St,40.721124,-74.038051,3275,Columbus Drive,40.718355,-74.038914,29480,Subscriber,1888,0
23768,214,2020-01-29 18:34:59.0040,2020-01-29 18:38:33.8310,3187,Warren St,40.721124,-74.038051,3186,Grove St PATH,40.719586,-74.043117,29197,Subscriber,1888,0

In [22]:
januaryBY = january_data.drop(january_data[january_data['birth year'] < 1919].index)

januaryBY['birth year'].min()

1938

In [23]:
januaryBY['tripduration'].max()

520598

In [24]:
januaryBY.loc[januaryBY['tripduration'] > 15000]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
1300,16693,2020-01-03 06:46:45.3900,2020-01-03 11:24:58.6010,3276,Marin Light Rail,40.714584,-74.042817,3214,Essex Light Rail,40.712774,-74.036486,29667,Subscriber,1986,1
3023,132652,2020-01-05 18:49:09.4650,2020-01-07 07:40:01.6080,3195,Sip Ave,40.730897,-74.063913,3186,Grove St PATH,40.719586,-74.043117,29531,Subscriber,1977,2
3053,40062,2020-01-05 19:59:58.7330,2020-01-06 07:07:41.0580,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,26290,Subscriber,1975,2
8722,72633,2020-01-11 14:58:56.3100,2020-01-12 11:09:29.6290,3195,Sip Ave,40.730897,-74.063913,3211,Newark Ave,40.721525,-74.046305,29654,Customer,1995,1
8772,190093,2020-01-11 15:23:33.9060,2020-01-13 20:11:47.3170,3192,Liberty Light Rail,40.711242,-74.055701,3192,Liberty Light Rail,40.711242,-74.055701,29462,Customer,1977,1
8784,61879,2020-01-11 15:28:52.8780,2020-01-12 08:40:12.0120,3639,Harborside,40.719252,-74.034234,3203,Hamilton Park,40.727596,-74.044247,29291,Subscriber,1959,2
8839,24706,2020-01-11 16:14:08.6080,2020-01-11 23:05:54.7500,3276,Marin Light Rail,40.714584,-74.042817,3187,Warren St,40.721124,-74.038051,29583,Customer,1994,1
9324,22822,2020-01-12 09:54:35.9770,2020-01-12 16:14:58.8640,3205,JC Medical Center,40.716540,-74.049638,3639,Harborside,40.719252,-74.034234,26238,Subscriber,1986,2
9588,75091,2020-01-12 13:26:03.3350,2020-01-13 10:17:35.0480,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3681,Grand St,40.715178,-74.037683,29502,Subscriber,1982,2
9682,150034,2020-01-12 14:30:53.2630,2020-01-14 08:11:27.5000,3205,JC Medical Center,40.716540,-74.049638,3205,JC Medical Center,40.716540,-74.049638,26224,Customer,1969,0
10047,68852,2020-01-12 20:19:08.4850,2020-01-13 15:26:41.0380,3193,Lincoln Park,40.724605,-74.078406,3193,Lincoln Park,40.724605,-74.078406,26180,Customer,1993,2
14923,152783,2020-01-17 21:44:00.7060,2020-01-19 16:10:23.9770,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,29513,Customer,1993,1
15740,22501,2020-01-20 08:47:39.9970,2020-01-20 15:02:41.2320,3186,Grove St PATH,40.719586,-74.043117,3270,Jersey & 6th St,40.725289,-74.045572,29209,Subscriber,1978,2
15761,114081,2020-01-20 09:21:09.1210,2020-01-21 17:02:30.8760,3273,Manila & 1st,40.721651,-74.042884,3192,Liberty Light Rail,40.711242,-74.055701,29608,Customer,1969,0
19072,17572,2020-01-24 01:30:27.6900,2020-01-24 06:23:20.1420,3194,McGinley Square,40.725340,-74.067622,3195,Sip Ave,40.730897,-74.063913,29276,Customer,1969,0
19592,520598,2020-01-24 15:10:41.5170,2020-01-30 15:47:20.1520,3280,Astor Place,40.719282,-74.071262,3679,Bergen Ave,40.722104,-74.071455,29596,Customer,1969,0
19886,220912,2020-01-24 18:32:13.5160,2020-01-27 07:54:06.2930,3203,Hamilton Park,40.727596,-74.044247,3186,Grove St PATH,40.719586,-74.043117,29255,Customer,1988,1
19992,76888,2020-01-24 19:57:24.3120,2020-01-25 17:18:53.2100,3199,Newport Pkwy,40.728745,-74.032108,3275,Columbus Drive,40.718355,-74.038914,29461,Customer,1992,2
21370,22184,2020-01-27 11:58:25.6480,2020-01-27 18:08:09.7730,3278,Monmouth and 6th,40.725685,-74.048790,3186,Grove St PATH,40.719586,-74.043117,26307,Subscriber,1975,2
24396,31018,2020-01-30 10:48:30.7120,2020-01-30 19:25:28.7480,3203,Hamilton Park,40.727596,-74.044247,3276,Marin Light Rail,40.714584,-74.042817,29640,Subscriber,1993,1

In [25]:
januaryClean = januaryBY.drop(januaryBY[januaryBY['tripduration'] > 15000].index)

januaryClean['tripduration'].max()

14984

In [26]:
januaryClean.describe()

,tripduration,start station id,start station latitude,start station longitude,end station id,end station latitude,end station longitude,bikeid,birth year,gender
count,25986.000000,25986.000000,25986.000000,25986.000000,25986.000000,25986.000000,25986.000000,25986.000000,25986.000000,25986.000000
mean,463.273493,3305.614369,40.722576,-74.046603,3305.262141,40.722259,-74.046202,29180.104248,1981.213961,1.200377
std,579.684591,184.042670,0.006671,0.010981,186.661252,0.006523,0.010890,3259.424182,10.083500,0.496811
min,61.000000,3184.000000,40.711130,-74.083639,525.000000,40.709651,-74.083639,26151.000000,1938.000000,0.000000
25%,225.000000,3195.000000,40.718355,-74.050444,3194.000000,40.718355,-74.050389,26303.000000,1976.000000,1.000000
50%,326.000000,3211.000000,40.721525,-74.043845,3211.000000,40.721124,-74.043117,29307.000000,1983.000000,1.000000
75%,501.000000,3276.000000,40.726012,-74.038526,3277.000000,40.726012,-74.038051,29571.000000,1989.000000,1.000000
max,14984.000000,3792.000000,40.748716,-74.032108,3792.000000,40.755942,-74.002116,42370.000000,2002.000000,2.000000

In [27]:
januaryClean['stoptime'].min()

'2020-01-01 00:08:37.0370'

In [28]:
januaryClean['stoptime'].max()

'2020-02-01 00:00:36.4060'

In [29]:
januaryClean['starttime'].min()

'2020-01-01 00:04:50.1920'

In [30]:
januaryClean['starttime'].max()

'2020-01-31 23:48:35.1700'

In [31]:
januaryClean['starttime'] = pd.to_datetime(januaryClean.starttime)
januaryClean.info('starttime')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25986 entries, 0 to 26019
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tripduration             25986 non-null  int64
 1   starttime                25986 non-null  datetime64[ns]
 2   stoptime                 25986 non-null  object
 3   start station id         25986 non-null  int64
 4   start station name       25986 non-null  object
 5   start station latitude   25986 non-null  float64
 6   start station longitude  25986 non-null  float64
 7   end station id           25986 non-null  int64
 8   end station name         25986 non-null  object
 9   end station latitude     25986 non-null  float64
 10  end station longitude    25986 non-null  float64
 11  bikeid                   25986 non-null  int64
 12  usertype                 25986 non-null  object
 13  birth year               25986 non-null  int64
 14  gender                   25986 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(6), object(4)
memory usage: 3.2+ MB

In [32]:
januaryClean['stoptime'] = pd.to_datetime(januaryClean.stoptime)
januaryClean.info('stoptime')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25986 entries, 0 to 26019
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tripduration             25986 non-null  int64
 1   starttime                25986 non-null  datetime64[ns]
 2   stoptime                 25986 non-null  datetime64[ns]
 3   start station id         25986 non-null  int64
 4   start station name       25986 non-null  object
 5   start station latitude   25986 non-null  float64
 6   start station longitude  25986 non-null  float64
 7   end station id           25986 non-null  int64
 8   end station name         25986 non-null  object
 9   end station latitude     25986 non-null  float64
 10  end station longitude    25986 non-null  float64
 11  bikeid                   25986 non-null  int64
 12  usertype                 25986 non-null  object
 13  birth year               25986 non-null  int64
 14  gender                   25986 non-null  int64
dtypes: datetime64[ns](2), float64(4), int64(6), object(3)
memory usage: 3.2+ MB

In [33]:
januaryClean.gender[januaryClean.gender == 0] = 'unknown'
januaryClean.gender[januaryClean.gender == 1] = 'male'
januaryClean.gender[januaryClean.gender == 2] = 'female'
januaryClean

C:\Users\Kim\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.192,2020-01-01 00:08:37.037,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,female
1,377,2020-01-01 00:16:01.670,2020-01-01 00:22:19.080,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,female
2,288,2020-01-01 00:17:33.877,2020-01-01 00:22:22.442,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,male
3,435,2020-01-01 00:32:05.902,2020-01-01 00:39:21.066,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,unknown
4,231,2020-01-01 00:46:19.678,2020-01-01 00:50:11.344,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26015,544,2020-01-31 23:29:29.391,2020-01-31 23:38:33.691,3213,Van Vorst Park,40.718489,-74.047727,3194,McGinley Square,40.725340,-74.067622,29659,Subscriber,1989,male
26016,122,2020-01-31 23:30:59.367,2020-01-31 23:33:01.687,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42361,Subscriber,1991,male
26017,201,2020-01-31 23:42:34.846,2020-01-31 23:45:55.878,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42368,Subscriber,1988,male
26018,300,2020-01-31 23:45:00.680,2020-01-31 23:50:00.874,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,42257,Subscriber,1981,female
26019,721,2020-01-31 23:48:35.170,2020-02-01 00:00:36.406,3206,Hilltop,40.731169,-74.057574,3202,Newport PATH,40.727224,-74.033759,29302,Customer,1998,male

In [34]:
from datetime import datetime as dt
dayOfWeek = januaryClean.starttime.dt.day_name()
januaryClean['dayOfWeek'] = dayOfWeek
januaryClean

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,dayOfWeek
0,226,2020-01-01 00:04:50.192,2020-01-01 00:08:37.037,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,female,Wednesday
1,377,2020-01-01 00:16:01.670,2020-01-01 00:22:19.080,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,female,Wednesday
2,288,2020-01-01 00:17:33.877,2020-01-01 00:22:22.442,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,male,Wednesday
3,435,2020-01-01 00:32:05.902,2020-01-01 00:39:21.066,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,unknown,Wednesday
4,231,2020-01-01 00:46:19.678,2020-01-01 00:50:11.344,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,female,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26015,544,2020-01-31 23:29:29.391,2020-01-31 23:38:33.691,3213,Van Vorst Park,40.718489,-74.047727,3194,McGinley Square,40.725340,-74.067622,29659,Subscriber,1989,male,Friday
26016,122,2020-01-31 23:30:59.367,2020-01-31 23:33:01.687,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42361,Subscriber,1991,male,Friday
26017,201,2020-01-31 23:42:34.846,2020-01-31 23:45:55.878,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42368,Subscriber,1988,male,Friday
26018,300,2020-01-31 23:45:00.680,2020-01-31 23:50:00.874,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,42257,Subscriber,1981,female,Friday
26019,721,2020-01-31 23:48:35.170,2020-02-01 00:00:36.406,3206,Hilltop,40.731169,-74.057574,3202,Newport PATH,40.727224,-74.033759,29302,Customer,1998,male,Friday

In [ ]:
#januaryClean.to_csv('Clean_Data/januaryCBClean.csv', mode = 'w', index=False)

In [ ]:
# Import Data
Data_To_Load2 = "citibike_data/JC-202003-citibike-tripdata.csv"

march_data = pd.read_csv(Data_To_Load2)

In [ ]:
march_data.describe()

In [ ]:
march_data.info()

In [ ]:
march_data.shape

In [ ]:
march_data.gender.value_counts(dropna=False)

In [ ]:
march_data.usertype.value_counts(dropna=False)

In [ ]:
march_data.bikeid.value_counts(dropna=False)

In [ ]:
march_data.min()

In [ ]:
march_data.max()

In [ ]:
march_data['birth year'].min()

In [ ]:
march_data['tripduration'].median()

In [ ]:
march_data['birth year'].tail()

In [ ]:
birthyearsort =march_clean.sort_values('birth year', ascending = True)
birthyearsort.head(100)

In [ ]:
march_data.loc[march_clean['birth year'] < 1919]

In [ ]:
marchBY = june_clean.drop(march_clean[march_clean['birth year'] < 1919].index)

In [ ]:
marchBY['birth year'].min()

In [ ]:
marchBY['birth year'].max()

In [ ]:
marchBY.loc[marchBY['tripduration'] > 15000]

In [ ]:
marchClean = marchBY.drop(marchBY[marchBY['tripduration'] > 15000].index)
marchClean.shape

In [ ]:
marchClean['tripduration'].max()

In [ ]:
marchClean.describe()

In [ ]:
marchClean['starttime'] = pd.to_datetime(marchClean.starttime)
marchClean.info('starttime')
marchClean['stoptime'] = pd.to_datetime(marchClean.stoptime)
marchClean.info('stoptime')

In [ ]:
marchClean.info()

In [ ]:
marchClean.gender[marchClean.gender == 0] = 'unknown'
marchClean.gender[marchClean.gender == 1] = 'male'
marchClean.gender[marchClean.gender == 2] = 'female'
marchClean

In [ ]:
dayOfWeek = marchClean.starttime.dt.day_name()
marchClean['dayOfWeek'] = dayOfWeek
marchClean

In [ ]:
marchClean['starttime'].max()

In [ ]:
marchClean['starttime'].min()

In [ ]:
marchClean['stoptime'].max()

In [ ]:
marchClean['stoptime'].min()

In [ ]:
#juneClean.to_csv('Clean_Data/juneCBClean.csv', mode = 'w', index=False)

In [ ]:

# Import Data
Data_To_Load2 = "Raw_Data/201909-citibike-tripdata.csv"

In [ ]:
sept_clean = pd.read_csv(Data_To_Load2)